.text

.globl f1
f1:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f1:
	leave
	ret


.globl f2
f2:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f2:
	leave
	ret


.globl f3
f3:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f3:
	leave
	ret


.globl f4
f4:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f4:
	leave
	ret


.globl f5
f5:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f5:
	leave
	ret


.globl f6
f6:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f6:
	leave
	ret


.globl f123
f123:
	pushq %rbp
	movq %rsp, %rbp


	# return ci0
	movl $0, %eax

return_f123:
	leave
	ret


